# Keep the auto-detected providers and add any additional ones if needed
providers = ["..."]

[phases.setup]
# The "..." ensures we keep any default packages while adding our own
aptPkgs = [
  "...",
  "chromium-browser", 
  "chromium-driver", 
  "libgconf-2-4", 
  "libnss3", 
  "libgbm1", 
  "libxss1", 
  "libasound2", 
  "libatk1.0-0", 
  "libatk-bridge2.0-0", 
  "libcups2", 
  "libdrm2", 
  "libxkbcommon0", 
  "libxcomposite1", 
  "libxdamage1", 
  "libxfixes3", 
  "libxrandr2", 
  "libpango-1.0-0"
]

# Ensure the ChromeDriver and Chromium binary locations are in the PATH
paths = ["/usr/bin"]

# You can leave the default start command from railway.toml
[start]
cmd = "uvicorn whatsapp_server:app --host 0.0.0.0 --port $PORT"
