   [build]
   builder = "nixpacks"

   [deploy]
   startCommand = "uvicorn whatsapp_server:app --host 0.0.0.0 --port $PORT"

    [phases.setup]
    aptPkgs = [
    "chromium-browser", 
    "chromium-driver", 
    "libgconf-2-4", 
    "libnss3", 
    "libgbm1", 
    "libxss1", 
    "libasound2", 
    "libatk1.0-0", 
    "libatk-bridge2.0-0", 
    "libcups2", 
    "libdrm2", 
    "libxkbcommon0", 
    "libxcomposite1", 
    "libxdamage1", 
    "libxfixes3", 
    "libxrandr2", 
    "libgbm1", 
    "libpango-1.0-0"
    ]
    paths = ["/usr/bin"]